# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QFrame,
    QGroupBox, QHeaderView, QLabel, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTableView, QTextEdit, QTreeView,
    QVBoxLayout, QWidget)

from centerOpenGLWidget import (ShowWidget3D, ShowWidgetXY, ShowWidgetXZ, ShowWidgetYZ)
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet(u"")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.ShowWidget = QWidget(self.centralWidget)
        self.ShowWidget.setObjectName(u"ShowWidget")
        self.ShowWidget.setGeometry(QRect(420, 0, 1080, 1039))
        self.ShowWidget_11_XY = QWidget(self.ShowWidget)
        self.ShowWidget_11_XY.setObjectName(u"ShowWidget_11_XY")
        self.ShowWidget_11_XY.setGeometry(QRect(20, 0, 500, 510))
        self.openGLWidget_XY = ShowWidgetXY(self.ShowWidget_11_XY)
        self.openGLWidget_XY.setObjectName(u"openGLWidget_XY")
        self.openGLWidget_XY.setGeometry(QRect(10, 30, 480, 480))
        self.openGLWidget_XY.setMinimumSize(QSize(480, 480))
        self.openGLWidget_XY.setMaximumSize(QSize(480, 480))
        self.ShowWidget_XY_label = QLabel(self.ShowWidget_11_XY)
        self.ShowWidget_XY_label.setObjectName(u"ShowWidget_XY_label")
        self.ShowWidget_XY_label.setGeometry(QRect(0, 0, 480, 30))
        self.ShowWidget_12_3D = QWidget(self.ShowWidget)
        self.ShowWidget_12_3D.setObjectName(u"ShowWidget_12_3D")
        self.ShowWidget_12_3D.setGeometry(QRect(560, 0, 500, 510))
        self.ShowWidget_12_3D.setStyleSheet(u"border-color: rgb(85, 255, 255);")
        self.openGLWidget_3D = ShowWidget3D(self.ShowWidget_12_3D)
        self.openGLWidget_3D.setObjectName(u"openGLWidget_3D")
        self.openGLWidget_3D.setGeometry(QRect(10, 30, 480, 480))
        self.openGLWidget_3D.setMinimumSize(QSize(480, 480))
        self.openGLWidget_3D.setMaximumSize(QSize(480, 480))
        self.ShowWidget_3D_label = QLabel(self.ShowWidget_12_3D)
        self.ShowWidget_3D_label.setObjectName(u"ShowWidget_3D_label")
        self.ShowWidget_3D_label.setGeometry(QRect(0, 0, 480, 30))
        self.ShowWidget_21_XZ = QWidget(self.ShowWidget)
        self.ShowWidget_21_XZ.setObjectName(u"ShowWidget_21_XZ")
        self.ShowWidget_21_XZ.setGeometry(QRect(20, 510, 500, 510))
        self.openGLWidget_XZ = ShowWidgetXZ(self.ShowWidget_21_XZ)
        self.openGLWidget_XZ.setObjectName(u"openGLWidget_XZ")
        self.openGLWidget_XZ.setGeometry(QRect(10, 30, 480, 480))
        self.openGLWidget_XZ.setMinimumSize(QSize(480, 480))
        self.openGLWidget_XZ.setMaximumSize(QSize(480, 480))
        self.ShowWidget_XZ_label = QLabel(self.ShowWidget_21_XZ)
        self.ShowWidget_XZ_label.setObjectName(u"ShowWidget_XZ_label")
        self.ShowWidget_XZ_label.setGeometry(QRect(0, 0, 480, 30))
        self.ShowWidget_22_YZ = QWidget(self.ShowWidget)
        self.ShowWidget_22_YZ.setObjectName(u"ShowWidget_22_YZ")
        self.ShowWidget_22_YZ.setGeometry(QRect(560, 510, 500, 510))
        self.openGLWidget_YZ = ShowWidgetYZ(self.ShowWidget_22_YZ)
        self.openGLWidget_YZ.setObjectName(u"openGLWidget_YZ")
        self.openGLWidget_YZ.setGeometry(QRect(10, 30, 480, 480))
        self.openGLWidget_YZ.setMinimumSize(QSize(480, 480))
        self.openGLWidget_YZ.setMaximumSize(QSize(480, 480))
        self.ShowWidget_YZ_label = QLabel(self.ShowWidget_22_YZ)
        self.ShowWidget_YZ_label.setObjectName(u"ShowWidget_YZ_label")
        self.ShowWidget_YZ_label.setGeometry(QRect(0, 0, 480, 30))
        self.LeftWidget = QWidget(self.centralWidget)
        self.LeftWidget.setObjectName(u"LeftWidget")
        self.LeftWidget.setGeometry(QRect(0, 0, 420, 1039))
        self.LeftWidget.setStyleSheet(u"")
        self.verticalLayout = QVBoxLayout(self.LeftWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.simulationFunctionTableWidget = QWidget(self.LeftWidget)
        self.simulationFunctionTableWidget.setObjectName(u"simulationFunctionTableWidget")
        self.simulationFunctionTableTitle = QLabel(self.simulationFunctionTableWidget)
        self.simulationFunctionTableTitle.setObjectName(u"simulationFunctionTableTitle")
        self.simulationFunctionTableTitle.setGeometry(QRect(0, 0, 400, 30))
        self.simulationFunctionTableTitle.setStyleSheet(u"background-color: rgb(45,48,51);")
        self.simulationFunctionTable = QGroupBox(self.simulationFunctionTableWidget)
        self.simulationFunctionTable.setObjectName(u"simulationFunctionTable")
        self.simulationFunctionTable.setGeometry(QRect(0, 30, 400, 311))
        self.pushButton = QPushButton(self.simulationFunctionTable)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(0, 0, 80, 80))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QSize(80, 80))
        self.pushButton.setStyleSheet(u"")
        self.pushButton_3 = QPushButton(self.simulationFunctionTable)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(160, 0, 80, 80))
        self.pushButton_5 = QPushButton(self.simulationFunctionTable)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(240, 0, 80, 80))
        self.pushButton_9 = QPushButton(self.simulationFunctionTable)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(80, 0, 80, 80))
        self.runButton = QPushButton(self.simulationFunctionTable)
        self.runButton.setObjectName(u"runButton")
        self.runButton.setGeometry(QRect(320, 0, 80, 80))
        self.pushButton_test = QPushButton(self.simulationFunctionTable)
        self.pushButton_test.setObjectName(u"pushButton_test")
        self.pushButton_test.setGeometry(QRect(0, 80, 75, 23))

        self.verticalLayout.addWidget(self.simulationFunctionTableWidget)

        self.toolBoxWidget = QWidget(self.LeftWidget)
        self.toolBoxWidget.setObjectName(u"toolBoxWidget")
        self.toolBoxTitle = QLabel(self.toolBoxWidget)
        self.toolBoxTitle.setObjectName(u"toolBoxTitle")
        self.toolBoxTitle.setGeometry(QRect(0, 0, 400, 30))
        self.toolBoxTitle.setStyleSheet(u"background-color: rgb(45,48,51);")
        self.pushButton_Object = QPushButton(self.toolBoxWidget)
        self.pushButton_Object.setObjectName(u"pushButton_Object")
        self.pushButton_Object.setGeometry(QRect(100, 30, 100, 80))
        self.pushButton_Region = QPushButton(self.toolBoxWidget)
        self.pushButton_Region.setObjectName(u"pushButton_Region")
        self.pushButton_Region.setGeometry(QRect(0, 30, 100, 80))
        self.pushButton_Detector = QPushButton(self.toolBoxWidget)
        self.pushButton_Detector.setObjectName(u"pushButton_Detector")
        self.pushButton_Detector.setGeometry(QRect(300, 30, 100, 80))
        self.pushButton_Source = QPushButton(self.toolBoxWidget)
        self.pushButton_Source.setObjectName(u"pushButton_Source")
        self.pushButton_Source.setGeometry(QRect(200, 30, 100, 80))
        self.pushButton_Mesh = QPushButton(self.toolBoxWidget)
        self.pushButton_Mesh.setObjectName(u"pushButton_Mesh")
        self.pushButton_Mesh.setGeometry(QRect(0, 110, 100, 80))
        self.pushButton_ObjectGroup = QPushButton(self.toolBoxWidget)
        self.pushButton_ObjectGroup.setObjectName(u"pushButton_ObjectGroup")
        self.pushButton_ObjectGroup.setGeometry(QRect(100, 110, 100, 80))

        self.verticalLayout.addWidget(self.toolBoxWidget)

        self.rightWidget = QWidget(self.centralWidget)
        self.rightWidget.setObjectName(u"rightWidget")
        self.rightWidget.setGeometry(QRect(1500, 0, 420, 1039))
        self.rightWidget.setStyleSheet(u"")
        self.verticalLayout_2 = QVBoxLayout(self.rightWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.objectTreeWidget = QWidget(self.rightWidget)
        self.objectTreeWidget.setObjectName(u"objectTreeWidget")
        self.objectTreeWidget.setStyleSheet(u"")
        self.objectTree = QTreeView(self.objectTreeWidget)
        self.objectTree.setObjectName(u"objectTree")
        self.objectTree.setGeometry(QRect(0, 65, 400, 335))
        self.objectTree.setDragEnabled(True)
        self.objectTree.setDragDropMode(QAbstractItemView.DragOnly)
        self.objectTree.setSortingEnabled(True)
        self.objectTree.setHeaderHidden(True)
        self.objectTreeTitle = QLabel(self.objectTreeWidget)
        self.objectTreeTitle.setObjectName(u"objectTreeTitle")
        self.objectTreeTitle.setGeometry(QRect(0, 0, 400, 30))
        self.objectTreeTitle.setStyleSheet(u"background-color: rgb(45,48,51);")
        self.objectFilter = QTextEdit(self.objectTreeWidget)
        self.objectFilter.setObjectName(u"objectFilter")
        self.objectFilter.setGeometry(QRect(0, 30, 400, 30))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.objectFilter.sizePolicy().hasHeightForWidth())
        self.objectFilter.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(9)
        self.objectFilter.setFont(font)
        self.objectFilter.setMouseTracking(True)
        self.objectFilter.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.objectFilter.setAcceptDrops(True)
        self.objectFilter.setStyleSheet(u"")
        self.objectFilter.setInputMethodHints(Qt.ImhMultiLine)
        self.objectFilter.setFrameShape(QFrame.Box)
        self.objectFilter.setFrameShadow(QFrame.Plain)
        self.objectFilter.setLineWidth(1)
        self.objectFilter.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.objectFilter.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.objectFilter.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.objectFilter.setLineWrapMode(QTextEdit.NoWrap)
        self.objectFilter.setLineWrapColumnOrWidth(0)
        self.objectFilter.setCursorWidth(1)
        self.pushButton_setObjectParameterTable = QPushButton(self.objectTreeWidget)
        self.pushButton_setObjectParameterTable.setObjectName(u"pushButton_setObjectParameterTable")
        self.pushButton_setObjectParameterTable.setGeometry(QRect(340, 400, 60, 60))

        self.verticalLayout_2.addWidget(self.objectTreeWidget)

        self.objectParameterWidget = QWidget(self.rightWidget)
        self.objectParameterWidget.setObjectName(u"objectParameterWidget")
        self.objectParameterWidget.setStyleSheet(u"")
        self.objectParameterTitle = QLabel(self.objectParameterWidget)
        self.objectParameterTitle.setObjectName(u"objectParameterTitle")
        self.objectParameterTitle.setGeometry(QRect(0, 0, 400, 30))
        self.objectParameterTitle.setStyleSheet(u"background-color: rgb(45,48,51);")
        self.objectParameterTable = QTableView(self.objectParameterWidget)
        self.objectParameterTable.setObjectName(u"objectParameterTable")
        self.objectParameterTable.setGeometry(QRect(0, 30, 400, 400))
        self.objectParameterTable.setBaseSize(QSize(0, 0))

        self.verticalLayout_2.addWidget(self.objectParameterWidget)

        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1920, 21))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Edit = QMenu(self.menubar)
        self.menu_Edit.setObjectName(u"menu_Edit")
        self.menu_View = QMenu(self.menubar)
        self.menu_View.setObjectName(u"menu_View")
        self.menu_Settings = QMenu(self.menubar)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionClose)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionNew.triggered.connect(MainWindow.setNewFile)
        self.actionOpen.triggered.connect(MainWindow.openFile)
        self.actionSave_as.triggered.connect(MainWindow.saveFileAs)
        self.actionSave.triggered.connect(MainWindow.saveFile)
        self.actionClose.triggered.connect(MainWindow.closeFile)
        self.runButton.clicked.connect(MainWindow.runFile)
        self.openGLWidget_XY.request_Repaint_Signal.connect(self.openGLWidget_XZ.update)
        self.openGLWidget_XY.request_Repaint_Signal.connect(self.openGLWidget_YZ.update)
        self.openGLWidget_XZ.request_Repaint_Signal.connect(self.openGLWidget_XY.update)
        self.openGLWidget_XZ.request_Repaint_Signal.connect(self.openGLWidget_YZ.update)
        self.openGLWidget_YZ.request_Repaint_Signal.connect(self.openGLWidget_XY.update)
        self.openGLWidget_YZ.request_Repaint_Signal.connect(self.openGLWidget_XZ.update)
        self.pushButton_Region.clicked.connect(MainWindow.addRegion)
        self.pushButton_Object.clicked.connect(MainWindow.addObject)
        self.pushButton_Source.clicked.connect(MainWindow.addSource)
        self.pushButton_Detector.clicked.connect(MainWindow.addDetector)
        self.pushButton_Mesh.clicked.connect(MainWindow.addMesh)
        MainWindow.request_Update_Signal.connect(self.openGLWidget_XY.update)
        MainWindow.request_Update_Signal.connect(self.openGLWidget_XZ.update)
        MainWindow.request_Update_Signal.connect(self.openGLWidget_YZ.update)
        self.pushButton_ObjectGroup.clicked.connect(MainWindow.addObjectGroup)
        self.pushButton_test.clicked.connect(MainWindow.test)
        self.pushButton_setObjectParameterTable.clicked.connect(MainWindow.setObjectParameterTable)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa(New)", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00(Open)", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58(Save)", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a...(Save As...)", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed(Close)", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa(Exit)", None))
        self.ShowWidget_XY_label.setText(QCoreApplication.translate("MainWindow", u"X-Y:", None))
        self.ShowWidget_3D_label.setText(QCoreApplication.translate("MainWindow", u"3D:", None))
        self.ShowWidget_XZ_label.setText(QCoreApplication.translate("MainWindow", u"X-Z:", None))
        self.ShowWidget_YZ_label.setText(QCoreApplication.translate("MainWindow", u"Y-Z:", None))
        self.simulationFunctionTableTitle.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\u529f\u80fd\u8868", None))
        self.simulationFunctionTable.setTitle("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u6750\u6599\u5e93", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u7ec4\u4ef6", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u5206\u6790\n"
"\u5de5\u5177", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\u7aef\u53e3", None))
        self.runButton.setText(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c", None))
        self.pushButton_test.setText(QCoreApplication.translate("MainWindow", u"test", None))
        self.toolBoxTitle.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\u5de5\u5177\u7bb1", None))
        self.pushButton_Object.setText(QCoreApplication.translate("MainWindow", u"\u7269\u4f53\n"
"Object", None))
        self.pushButton_Region.setText(QCoreApplication.translate("MainWindow", u"\u4eff\u771f\n"
"\u533a\u57df\n"
"Region", None))
        self.pushButton_Detector.setText(QCoreApplication.translate("MainWindow", u"\u76d1\u89c6\u5668\n"
"Detector", None))
        self.pushButton_Source.setText(QCoreApplication.translate("MainWindow", u"\u6e90\n"
"Source", None))
        self.pushButton_Mesh.setText(QCoreApplication.translate("MainWindow", u"\u7ec6\u5316\n"
"\u4eff\u771f\u533a\u57df\n"
"Mesh", None))
        self.pushButton_ObjectGroup.setText(QCoreApplication.translate("MainWindow", u"\u7269\u4f53\u7ec4\n"
"ObjectGroup", None))
        self.objectTreeTitle.setText(QCoreApplication.translate("MainWindow", u"\u5bf9\u8c61\u68c0\u67e5\u5668", None))
        self.objectFilter.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8fc7\u6ee4\u5668", None))
        self.pushButton_setObjectParameterTable.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u5c5e\u6027", None))
        self.objectParameterTitle.setText(QCoreApplication.translate("MainWindow", u"\u5c5e\u6027\u7f16\u8f91\u5668", None))
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6(File)", None))
        self.menu_Edit.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91(Edit)", None))
        self.menu_View.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe(View)", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e(Setting)", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9(Help)", None))
    # retranslateUi

